# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base"
  amd64: "ghcr.io/home-assistant/amd64-base"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: FRStack"
  org.opencontainers.image.description: "Run local instance of FRStackWebApi to communicate with Flex radio."
  org.opencontainers.image.source: "https://github.com/m5kvk-ham-radio-addons/frstack"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
  API_VERSION: "4_0_0_5"
  SDK_VERSION: "9.0.13"
  BASE_TAG: "3.15"
